# Generated by Django 3.1.13 on 2021-12-01 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='FlatPage',
        ),
    ]
