# Generated by Django 3.1.13 on 2022-01-31 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.flatpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.flatpage',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.flatpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.flatpage',),
        ),
        migrations.CreateModel(
            name='GetInvolvedPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.flatpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.flatpage',),
        ),
        migrations.CreateModel(
            name='OnlineCoursesPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.flatpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.flatpage',),
        ),
        migrations.CreateModel(
            name='TrainingProgramsPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.flatpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.flatpage',),
        ),
    ]
