# Generated by Django 3.1.13 on 2022-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220909_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='lang',
            field=models.TextField(choices=[('EN', 'English'), ('FR', 'French')], default='EN', max_length=2),
        ),
    ]
