# Generated by Django 3.1.13 on 2022-09-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogcategory_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='lang',
            new_name='language',
        ),
    ]
