# Generated by Django 3.1.13 on 2022-04-13 11:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_metadata_fieled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
