# Generated by Django 3.1.13 on 2022-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220912_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.TextField(choices=[('ENGLISH', 'English'), ('FRENCH', 'French')], default='ENGLISH', max_length=10),
        ),
    ]
