# Generated by Django 3.1.13 on 2022-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220912_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.TextField(choices=[('English', 'English'), ('French', 'French')], default='English', max_length=10),
        ),
    ]
