exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 0.7.0
    hooks:
      - id: djlint-django
      - id: djlint-django
        args: ['.', '--reformat']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [css, javascript]

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '8f63da4'
    hooks:
      - id: stylelint
        additional_dependencies: ['stylelint', 'stylelint-prettier', 'stylelint-config-prettier']

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.58.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
