---

- name: Checkout repo
  git:
    repo: https://github.com/{{ repo_name }}.git
    accept_hostkey: yes
    dest: "{{ repo_folder }}/"
    version: "{{ repo_branch }}"
    # key_file: /home/{{ create_user }}/.ssh/id_rsa.github
