from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name="about"),
    path(
        "events/",
        TemplateView.as_view(template_name="home/event_index_page.html"),
        name="events",
    ),
    path(
        "gdpr/",
        TemplateView.as_view(template_name="home/static_gdpr.html"),
        name="gdpr",
    ),
    path(
        "terms-conditions/",
        TemplateView.as_view(template_name="home/static_terms.html"),
        name="terms-conditions",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="home/static_contact.html"),
        name="contact",
    ),
    path(
        "moocs/",
        TemplateView.as_view(template_name="home/moocs.html"),
        name="moocs",
    ),
    path(
        "integration-of-open-data-and-artificial-intelligence-in-the-development-of-smart-cities-in-Africa/",
        TemplateView.as_view(template_name="home/events/1st_webinar.html"),
        name="integration-of-open-data-and-artificial-intelligence-in-the-development-of-smart-cities-in-Africa",
    ),
    path(
        "african-cities-what-role-for-the-youth/",
        TemplateView.as_view(template_name="home/events/2nd_webinar.html"),
        name="african-cities-what-role-for-the-youth",
    ),
    path(
        "how-to-build-resilient-african-cities/",
        TemplateView.as_view(template_name="home/events/3rd_webinar.html"),
        name="how-to-build-resilient-african-cities",
    ),
    path(
        "webinar-registration/",
        TemplateView.as_view(template_name="home/webinar_form.html"),
        name="webinar-registration",
    ),
    path("webinar-subscribe/", views.subscribe_webinar, name="subscribe-webinar"),
    path(
        "african-cities-conference-2023/",
        TemplateView.as_view(template_name="home/events/civa/civa.html"),
        name="african-cities-conference-2023",
    ),
    path(
        "african-cities-conference-2023-agenda/",
        TemplateView.as_view(template_name="home/events/civa/agenda.html"),
        name="acc-agenda",
    ),
    path(
        "african-cities-conference-2023-speakers/",
        TemplateView.as_view(template_name="home/events/civa/speakers.html"),
        name="acc-speakers",
    ),
    path(
        "african-cities-conference-2023-sponsors/",
        TemplateView.as_view(template_name="home/events/civa/sponsors.html"),
        name="acc-sponsors",
    ),
    path(
        "african-cities-conference-2023-contact/",
        TemplateView.as_view(template_name="home/events/civa/contact.html"),
        name="acc-informations",
    ),
    path(
        "african-cities-conference-2023-registration/",
        TemplateView.as_view(template_name="home/events/civa/form.html"),
        name="acc-registration",
    ),
    path(
        "african-cities-conference-2023-special-guests/",
        TemplateView.as_view(template_name="home/events/civa/guests.html"),
        name="acc-guests",
    ),
    path(
        "african-cities-conference-2023-commitee/",
        TemplateView.as_view(template_name="home/events/civa/commitee.html"),
        name="acc-commitee",
    ),
    path(
        "african-cities-conference-2023-call-for-papers/",
        TemplateView.as_view(template_name="home/events/civa/call-for-paper.html"),
        name="acc-papers",
    ),
    # Moocs url
    path(
        "moocs/introduction-a-la-planification-urbaine/",
        TemplateView.as_view(
            template_name="home/moocs/introduction_a_la_planification_urbaine.html"
        ),
        name="introduction-a-la-planification-urbaine",
    ),
    path(
        "moocs/planification-a-la-gestion-urbaine/",
        TemplateView.as_view(template_name="home/moocs/planification_a_la_gestion_urbaine.html"),
        name="planification-a-la-gestion-urbaine",
    ),
    path(
        "moocs/mobilites-et-transports-urbains/",
        TemplateView.as_view(
            template_name="home/moocs/mobilites_et_transports_urbains.html"
        ),
        name="mobilites-et-transports-urbains",
    ),
    path(
        "moocs/systemes-dinformation-geographique-partie-1/",
        TemplateView.as_view(
            template_name="home/moocs/systemes_dinformation_geographique_1.html"
        ),
        name="systemes-dinformation-geographique-partie-1",
    ),
    path(
        "moocs/systemes-dinformation-geographique-partie-2/",
        TemplateView.as_view(
            template_name="home/moocs/systemes_dinformation_geographique_2.html"
        ),
        name="systemes-dinformation-geographique-partie-2",
    ),
    path(
        "moocs/restructuration-des-quartiers-precaires/",
        TemplateView.as_view(
            template_name="home/moocs/restructuration_des_quartiers_precaires.html"
        ),
        name="restructuration-des-quartiers-precaires",
    ),
    path(
        "moocs/environnement-et-enjeux-de-developpement-durable/",
        TemplateView.as_view(template_name="home/moocs/environnement_et_enjeux_de_developpement_durable.html"),
        name="environnement-et-enjeux-de-developpement-durable",
    ),
    ########
    path("moocs/subscribe/", views.subscribe_moocs, name="subscribe-moocs"),
]
