all:
  children:
    local:
      hosts:
        localhost
    production:
      hosts:
        africancitieslab.org:
          ansible_become: 'true'
          ansible_become_user: root
          create_user: martibosch
          repo_branch: main
          repo_folder: /srv/african-cities-lab-org
          repo_name: martibosch/african-cities-lab-org
          envs_dir: .envs
    staging:
      hosts:
        staging.africancitieslab.org:
          ansible_become: 'true'
          ansible_become_user: root
          create_user: martibosch
          repo_branch: main
          repo_folder: /srv/african-cities-lab-org
          repo_name: martibosch/african-cities-lab-org
          envs_dir: .envs
    ungrouped: {}
